_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
                - 106
            "3":
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.0
            "6": 4.47.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
learning_rate:
    value: 1e-05
num_train_epochs:
    value: 1000
resolution:
    value: 512
train_batch_size:
    value: 1
