_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
                - 98
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
                - 98
                - 106
            "3":
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.7
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
learning_rate:
    value: 5e-05
num_train_epochs:
    value: 2000
resolution:
    value: 512
train_batch_size:
    value: 1
